version: '3.4'

services:
  product-db:
    container_name: product
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: TesT111t
    ports:
      - "1434:1433"
  product-api:
    image: product:latest
    environment:
      ConnectionStrings__Product: "Data Source=db,1433;Initial Catalog=Product;uid=sa;pwd=TesT111t!;Integrated Security=false;MultipleActiveResultSets=True"
    build:
      context: .
      dockerfile: Product.Api/Dockerfile
    depends_on:
      - product-db
  review-db:
    container_name: review
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: TesT111t
    ports:
      - "1435:1433"
  review-api:
    image: review:latest
    environment:
      ConnectionStrings__Review: "Data Source=db,1433;Initial Catalog=Review;uid=sa;pwd=TesT111t!;Integrated Security=false;MultipleActiveResultSets=True"
    build:
      context: .
      dockerfile: Review.Api/Dockerfile
    depends_on:
      - review-db
