version: '3.4'

services:
  db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: TesT111t
    ports:
      - "1433:1433"
  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Product.Api/Dockerfile
    depends_on:
      - db
